# Generated by Django 2.0.5 on 2018-05-16 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddm', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataEntryPairs',
            new_name='DataEntryPair',
        ),
    ]
