# Generated by Django 2.0.5 on 2018-05-16 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ddm', '0002_auto_20180516_0445'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataentry',
            name='project',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='ddm.Project'),
        ),
        migrations.AlterField(
            model_name='dataentrypair',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='ddm.DataEntry'),
        ),
        migrations.AlterField(
            model_name='dataentrypair',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='ddm.DataEntry'),
        ),
    ]
