# Generated by Django 2.0.5 on 2018-05-30 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddm', '0003_auto_20180516_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataentrypair',
            name='lower_limit',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='dataentrypair',
            name='mandatory',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='dataentrypair',
            name='optional',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='dataentrypair',
            name='upper_limit',
            field=models.NullBooleanField(default=None),
        ),
    ]
