# Generated by Django 2.0.5 on 2018-06-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddm', '0004_auto_20180530_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentrypair',
            name='lower_limit',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='dataentrypair',
            name='upper_limit',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
