# Generated by Django 2.0.5 on 2018-06-03 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ddm', '0005_auto_20180603_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataentrypair',
            name='project',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='ddm.Project'),
            preserve_default=False,
        ),
    ]
